// Load all the controllers within this directory
// This file is auto-generated by Stimulus. If you'd like to change any of this,
// look at installing this package as a dependency in package.json instead.

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { application } from "controllers/application"

// Eager load all controllers
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
